"""add job model

Revision ID: a1e36c556a09
Revises: c15c7c3b083e
Create Date: 2025-02-19 17:54:51.172897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e36c556a09'
down_revision = 'c15c7c3b083e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('required_skills', sa.String(length=500), nullable=True),
    sa.Column('preferred_skills', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('remote_type', sa.String(length=20), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('equity_offered', sa.Boolean(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('company_funding', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
